using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Sharp.CMS.Models.Page;

namespace Sharp.CMS.Models.InnerPage
{
    [Table("InnerPage")]
    public class InnerPageModel
    {
        [Key]
        public int InnerPageId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public int? Status { get; set; }
        public bool IsPublished { get; set; } = false;
        public bool IsHidden { get; set; } = false;
        public int? SortOrder { get; set; }
        public bool OpenInNewTab { get; set; } = false;
        public bool IsNew { get; set; } = false;
        public string Permalink { get; set; }
        public string AutoGeneratedlink { get; set; }
        public string MenuName_EN { get; set; }
        public string MenuName_LL { get; set; }
        public string PageTitle_EN { get; set; }
        public string PageTitle_LL { get; set; }
        public string PageName { get; set; }
        public InnerPageDetailsModel PageDetails { get; set; }
        public bool IsActive { get; set; }
        public int PageId { get; set; }
    }
}