using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sharp.CMS.Models.Page
{
    [Table("Page")]
    public class PageModel
    {
        [Key]
        public int PageId { get; set; }
        public DateTime? CreatedOn { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? ModifiedBy { get; set; }
        public int? Status { get; set; }
        public bool IsPublished { get; set; } = false;
        public bool IsHidden { get; set; } = false;
        public int? SortOrder { get; set; }
        public bool OpenInNewTab { get; set; } = false;
        public bool IsNew { get; set; } = false;
        public string Permalink { get; set; }
        public string AutoGeneratedlink { get; set; }
        public string MenuName_EN { get; set; }
        public string MenuName_LL { get; set; }
        public string PageTitle_EN { get; set; }
        public string PageTitle_LL { get; set; }
        public string PageName { get; set; }
        public  PageDetailsModel PageDetails { get; set; }
        public bool IsActive { get; set; }
        public bool IsChildPage { get; set; }
        public int? ParentPageId { get; set; }
        public bool IsHomePage { get; set; }
        public bool IsSubChildPage { get; set; }
        

    }
}